### ISSUE TITLE
building vtk wheels

### ISSUE THREAD

**Issue by xoviat** [MacPython/scipy-wheels#10]
@matthew-brett One popular library that isn't currently on pypi is the Visualization Toolkit (MIT license). What I propose here is creating a new repository under MacPython (you can grant me rights to that repository) that builds VTK wheels and then uploads them to pypi. The package can simply be called "VTK."

Basic process is not more complex compared to say, building scipy:
1. checkout VTK submodule
2. configure cmake
3. setup.py bdist_wheel

I'm not completely sure, but there may be copying DLLs required that need to be added to the path. Once set up, this repository should require near-zero maintenance other than updating the build_commit.

**Comment by matthew-brett** [comment]
There's actually been quite a lot of discussion on that with the VTK people.  Would you consider getting onto the VTK mailing list and bringing it up there?

**Comment by xoviat** [comment]
Sure. I actually considered doing this unilaterally but it's better to have consensus.

**Comment by matthew-brett** [comment]
I'm absolutely on for helping however I can - the problems seem to be do so with the various backends they need to support.  So I'll join in the conversation on the mailing list, if that would help.  I was in a conference call with them during Scipy about this.

**Comment by xoviat** [comment]
Actually, now that I think about it, VTK takes quite a while to compile. I wonder if appveyor would be able to manage within the time limits?

@matthew-brett Do you have owner privileges on this organization? Can you create the repository?

**Comment by xoviat** [comment]
Actually, the correct repository is here: https://github.com/jcfr/VTKPythonPackage
