### ISSUE TITLE
MAINT: move off Travis CI

### ISSUE THREAD

**Issue by tylerjereddy** [MacPython/scipy-wheels#106]
If we exceed our Travis CI quota before 1.6.0 is released, we could be in a bit of trouble for getting wheels out in a timely fashion.

See: https://github.com/scipy/scipy/issues/13109

Also, for some of the more exotic platforms like ARM we'd probably need to migrate to more than just 1 other service.

**Comment by muizzk** [comment]
Hello folks, please note that I have added additional credits to this project as directed. Thank you 

cc: @pauladamgordon

**Comment by rgommers** [comment]
That's great, thank you @muizzk

**Comment by tylerjereddy** [comment]
should we disable our Tuesday cron jobs for now?

**Comment by rgommers** [comment]
I'm not a MacPython admin I think. @matthew-brett can you see these credits and check how many runs we can approximately do?

> should we disable our Tuesday cron jobs for now?

makes sense, only PRs for now

**Comment by mattip** [comment]
@muizzk how can we check our credits?

**Comment by mattip** [comment]
I think it should be somewhere on https://travis-ci.com/github/MacPython/scipy-wheels/settings, but I don't see it there.

**Comment by janaknat** [comment]
@mattip The admin can see the credits at https://travis-ci.com/account/plan

**Comment by mattip** [comment]
Nope, I don't see the credits there. I only see the options to choose one of the plans.

**Comment by rgommers** [comment]
@mattip the right link may be https://travis-ci.com/organizations/macpython/plan

**Comment by charris** [comment]
387,410 credits remaining, they gave us 400,000.

**Comment by mattip** [comment]
Yup -- https://travis-ci.com/organizations/MacPython/plan. So that must be for all the macpython builders:
h5py-wheels
matplotlib-wheels
numpy-wheels
openblas-libs
pandas-wheels
scipy-wheels
statsmodels-wheels

**Comment by rgommers** [comment]
That's nice. We may want to disable daily cron jobs if there are any. With just PRs and weekly jobs, that should last a while.

**Comment by tylerjereddy** [comment]
I deleted the Travis cron for SciPy side of things at least

**Comment by mattip** [comment]
If I understand correctly, MacPython has already used 157,590 of the 510,000 credits we were given today (Nov 26), leaving 352,410. According to https://travis-ci.com/github/MacPython, that is the result of one run of scipy-wheels and one run of pandas-wheels.

**Comment by rgommers** [comment]
That doesn't sound right, 10K credits should be 1000 build minutes on Linux.

**Comment by mattip** [comment]
The [matplotlib-wheels build that ran a little while ago](https://travis-ci.com/github/MacPython/matplotlib-wheels/builds/204566949) drove down the credits to by 2320 to 350090. It ran for 43 minutes on x86 linux, 53 minutes on arm64, and 25 minutes on macOSx. I will continue to try to track this over the next day or two.

**Comment by rgommers** [comment]
macOS is 5x more expensive in credits than Linux, so that sounds about right. ~2000-2500 credits/build is what I calculated for SciPy as well. So 400K credits is ~175 builds, split over 7 projects for MacPython - meaning we've got roughly 25 builds per project left. Enough to get the next releases out the door and last a few months, if we make sure cron jobs don't run more than once a week I'd say.

**Comment by mattip** [comment]
There are projects running daily or more builds. We now are on 311,290 credits, down ~40,000 from the last check. At this rate we will run out of credits very soon. This includes:
- a run of numpy-wheels for ~70 minutes on arm64 (seems about as minimal as possible: one run a week on arm64)
- a [run of statsmodels-wheels](https://travis-ci.com/github/MacPython/statsmodels-wheels) for ~160min on x86 and 56 minutes on macOSx @matthew-brett could you move this to azure/github actions?
- 5 [runs of pandas-wheels](https://travis-ci.com/github/MacPython/pandas-wheels/builds) for ~90 minutes each on arm64 @simonjayhawkins could you reduce the frequency or is this work needed for a release?
- two more [runs of matplotlib-wheels](https://travis-ci.com/github/MacPython/matplotlib-wheels/builds) which seem to be on a daily cron job. @tacaswell could you reduce the frequency and move things off travis?

**Comment by simonjayhawkins** [comment]
Matti,

Have removed the Travis cron job as wheels weren't being built anyway,
https://github.com/MacPython/pandas-wheels/issues/102

There probably won't be many more pushes (if any) in prep for the release.
Was just tidying and testing and didn't realize there were usage limits.
Could maybe turn off Travis for pull requests and only enable when changes
are specifically targeted at the arm builds)

Hope this helps. Let me know if anything more is needed.

Simon

**Comment by mattip** [comment]
We have burned through another 100,000 credits and our balance now stands on 198,370. In the past 4 days [we had](https://travis-ci.com/github/MacPython/):
- a run of numpy-wheels on arm64 for about 60 minutes.
- a weekly cron job run of matplotlib-wheels.

I am not sure what is going on with the credits, maybe the macpython account is a joint one with other projects? In any case, we may run out of credits before the scipy and numpy releases in the coming weeks.

**Comment by rgommers** [comment]
The "Insights" tab helps give an overview:

<img width="766" alt="image" src="https://user-images.githubusercontent.com/98330/100947576-30d0d380-3506-11eb-93e8-61eb17c8e34c.png">

Perhaps your check was before those pandas builds were turned off. If so, that still doesn't quite add up to 100,000 though.

**Comment by rgommers** [comment]
No longer using TravisCI, closing.
