### ISSUE TITLE
BUG: CI upload failures observed for SciPy 1.6.2 wheel builds

### ISSUE THREAD

**Issue by tylerjereddy** [MacPython/scipy-wheels#115]
@ogrisel @rgommers @mattip This is showing up for Travis and Appveyor but not Azure as far as I can tell.

Maybe we're getting burned for using bleeding-edge `pip install git+https` for the client, which in turn depends on something unreleased now?

Travis build: https://travis-ci.com/github/MacPython/scipy-wheels/builds/220750268
Appveyor build: https://ci.appveyor.com/project/scipy/scipy-wheels/builds/38331654
Azure build: https://dev.azure.com/numpy/numpy/_build/results?buildId=16267&view=results

Example error:

```
$ if [ "$TRAVIS_EVENT_TYPE" == "push" ]; then ANACONDA_ORG="multibuild-wheels-staging"; pip install git+https://github.com/Anaconda-Server/anaconda-client; anaconda -t ${SCIPY_STAGING_UPLOAD_TOKEN} upload --force -u ${ANACONDA_ORG} ${TRAVIS_BUILD_DIR}/wheelhouse/*.whl; fi

Collecting git+https://github.com/Anaconda-Server/anaconda-client

  Cloning https://github.com/Anaconda-Server/anaconda-client to /tmp/pip-req-build-_y__2_b9

  Running command git clone -q https://github.com/Anaconda-Server/anaconda-client /tmp/pip-req-build-_y__2_b9

Collecting clyent>=1.2.0

  Downloading clyent-1.2.1.tar.gz (20 kB)

Collecting nbformat>=4.4.0

  Downloading nbformat-5.1.2-py3-none-any.whl (113 kB)

Collecting python-dateutil>=2.6.1

  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)

ERROR: Could not find a version that satisfies the requirement anaconda-project>=0.9.1 (from anaconda-client)

ERROR: No matching distribution found for anaconda-project>=0.9.1
```

**Comment by tylerjereddy** [comment]
Maybe the `anaconda-client` version we need is available as a stable release now?

**Comment by rgommers** [comment]
`anaconda-client` hasn't been released to PyPI for years, and `anaconda-project` is not on PyPI at all. Looks like we should pick the latest stable `anaconda-client` release from GitHub, and if that recently added an `anaconda-project` dependency, install it from GitHub too - or pick the latest `anaconda-client` that does not have that dependency.

**Comment by tylerjereddy** [comment]
Looks like it was a recent `requirements.txt` addition--I'll try pinning to the commit hash before that change for a first pass (see commit cross-listed above).
