### ISSUE TITLE
universal2 wheels need to be renamed to `...12_0...`

### ISSUE THREAD

**Issue by rgommers** [MacPython/scipy-wheels#148]
This is a follow up to gh-147 that is needed. `arm64` were renamed to ensure they can only be installed on macOS >= 12.0, however `universal2` wheels need to be renamed in the same way.

**Comment by tylerjereddy** [comment]
I'm going to reopen this because we'd like to use the upstream `multibuild` approach similar to https://github.com/MacPython/scipy-wheels/pull/150 with `MACOSX_DEPLOYMENT_TARGET` to rename/retarget the wheels.

That said, the evidence suggest our current "in house" approach is working in CI logs.

**Comment by rgommers** [comment]
No longer using multibuild and no longer producing universal2 wheels, so closing.
