### ISSUE TITLE
MAINT: wheels too large to upload

### ISSUE THREAD

**Issue by tylerjereddy** [MacPython/scipy-wheels#154]
`scipy-1.8.0rc1-cp310-cp310-macosx_12_0_universal2.whl` is 111 MB and the upload command with `twine` sends back:

```
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
File too large. Limit for project 'scipy' is 100 MB. See https://pypi.org/help/#file-size-limit for more information.
```

**Comment by tylerjereddy** [comment]
@rgommers I will open an issue per instructions here about getting our file size limit bumped a bit: https://pypi.org/help/#file-size-limit

Perhaps there are steps we could take to reduce the sizes of the binaries, although even the non-universal2 versions are skating pretty close to the limit (`scipy-1.8.0rc1-cp310-cp310-macosx_10_9_x86_64.whl` is 92 MB).

**Comment by tylerjereddy** [comment]
see: https://github.com/pypa/pypi-support/issues/1527

**Comment by tylerjereddy** [comment]
our limit was bumped to 125 MB by PyPA

**Comment by rgommers** [comment]
Hmm yes, that is getting a little large. `universal2` should go away longer term, or we can just stop uploading it if it really becomes a problem. But 92 MB for the `x86_64` wheel is a bug, it looks like we didn't strip it correctly. For `1.7.3` it's only 33 MB: https://pypi.org/project/scipy/1.7.3/#files

**Comment by rgommers** [comment]
The other option is we're installing way too much from one of the new submodules. Maybe large data files in `sparse/linalg/_PROPACK` - a quick check says it's ~150 MB on disk.

**Comment by rgommers** [comment]
Okay, all the wheels are way too large and it is `_propack`. The Examples are absolutely huge. Unpacking one of the `1.8.0rc1` wheels, `_propack` is 165 MB out of 259 MB for the whole wheel.

xref https://github.com/scipy/scipy/pull/14433 for the PROPACK addition, I don't see any discussion on file sizes there (but the review is large, I could have missed it). @mckib2, @mdhaber what is going on here? Why did we commit examples this large, and can we delete them?

**Comment by tupui** [comment]
There was a small discussion starting here https://github.com/scipy/scipy/pull/14433#pullrequestreview-734302772

**Comment by rgommers** [comment]
Hmm, https://github.com/scipy/scipy/pull/14433#issuecomment-902828640 by @dhermes suggests that that data was converted to `.npz`, but those `.npz` files are nowhere to be found and the `.ascii` files ended up in the repo.

**Comment by tupui** [comment]
> Hmm, https://github.com/scipy/scipy/pull/14433#issuecomment-902828640 by @dhermes suggests that that data was converted to `.npz`, but those `.npz` files are nowhere to be found and the `.ascii` files ended up in the repo.

Strange indeed, the diff on the PR shows the npz (from the view I have on my phone).

**Comment by mckib2** [comment]
I remember taking a look at an individual one and finding it was comparable to some of the benchmark data we have, but I could have been mistaken and/or there are more examples than are reasonable to be included in a source distribution of scipy.  Quickest/easiest fix I can think of is removing the examples directories from [our PROPACK repo](https://github.com/scipy/PROPACK).  I believe there shouldn't be any included history due to the options in the .gitmodules file for _propack.  May need to adjust some tests to avoid using the data that isn't there

**Comment by mdhaber** [comment]
> I just took a look, the only npz in the PR is 276 KB, so I believe the source of the unwanted weight must be the PROPACK submodule examples

I think that's right. The NPZ file we discussed in gh-14433 is in the [benchmarks directory](https://github.com/scipy/scipy/tree/master/benchmarks/benchmarks/svds_benchmark_files). The large example files are not in the SciPy repo directly; they are in the PROPACK submodule.

**Comment by tupui** [comment]
The last huge files I saw included were in the PR https://github.com/scipy/scipy/pull/15135

**Comment by mckib2** [comment]
The large PROPACK files have now been removed via gh-15214, will that be enough to resolve this issue?

**Comment by rgommers** [comment]
Yes it will, thanks @mckib2!
