### ISSUE TITLE
BUG: all 64-bit Windows wheel builds are failing

### ISSUE THREAD

**Issue by tylerjereddy** [MacPython/scipy-wheels#159]
- `1.8.0rc2` appveyor build matrix: https://ci.appveyor.com/project/scipy/scipy-wheels/builds/41957637
- from a `git diff ...` of the `1.8.0rc1` vs. `1.8.0rc2` Python 3.9 64-bit build logs, I find the following notable differences:
  - setuptools `59.5.0` vs. setuptools `60.0.1`
  - cython 0.29.25 vs. cython 0.29.26
  - pythran 0.10.0 vs 0.11.0
- I suspect we're getting prohibited versions of those deps because `python setup.py bdist_wheel` is used instead of i.e., `pip wheel` or `pip install` type commands that go through `pyproject.toml`? the appveyor config probably needs an update---if I can cheat and pin the deps another way for now I may do that, but complete resolution of this issue probably means modernizing the build approach (and we plan on replacing appveyor eventually anyway I think...)

**Comment by rgommers** [comment]
Definitely pin `setuptools` - `60.0.0` re-enabled its vendored `distutils` copy, and that will almost certainly break things.

**Comment by rgommers** [comment]
Fixed in our `cibuildwheel` builds, so closing.
