### ISSUE TITLE
BUG: MacOS/Linux wheels are misnamed

### ISSUE THREAD

**Issue by tylerjereddy** [MacPython/scipy-wheels#168]
The wheel names start with `SciPy-` instead of `scipy`: https://anaconda.org/multibuild-wheels-staging/scipy/files

I observed identical behavior locally with `paver release` until I pinned `setuptools < 60.0.0`.

Windows just got setuptools pinned for other reasons, I'll try to see if I have an option to pin for the Linux/Mac builds as well (on the release wheels branch for now...). I'll probably leave this open as a reminder for the 1.9.0 release if that doesn't use `cibuildwheel`.

**Comment by tylerjereddy** [comment]
I've tried pushing this right into `v1.8.x` in wheels repo:

```diff
--- a/azure-posix.yml
+++ b/azure-posix.yml
@@ -60,7 +60,8 @@ jobs:
           set -ex
           echo building for commit "$BUILD_COMMIT"
 
-          pip install --upgrade virtualenv wheel setuptools
+          pip install --upgrade virtualenv wheel
+          pip install "setuptools<60.0.0"
           BUILD_DEPENDS="wheel oldest-supported-numpy Cython>=0.29.24 pybind11>=2.4.3 pythran"
 
           source multibuild/common_utils.sh

```

**Comment by rgommers** [comment]
Ugh, I guess we split off 1.8.x before adding more setuptools pins - it should be pinned everywhere, >= 60.0 is broken.

**Comment by tylerjereddy** [comment]
My push had no effect:

```
2022-05-16T17:27:39.0359630Z + /Users/runner/hostedtoolcache/Python/3.10.4/x64/bin/python -m pip install /Users/runner/work/1/s/wheelhouse/SciPy-1.8.1-cp310-cp310-macosx_10_9_x86_64.whl
2022-05-16T17:27:39.7066230Z Processing ./wheelhouse/SciPy-1.8.1-cp310-cp310-macosx_10_9_x86_64.whl
2022-05-16T17:27:39.7518130Z Requirement already satisfied: numpy<1.25.0,>=1.17.3 in /Users/runner/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages (from SciPy==1.8.1) (1.21.6)
2022-05-16T17:27:40.0352210Z Installing collected packages: SciPy
2022-05-16T17:27:44.2305090Z Successfully installed SciPy-1.8.1
```

Shortly above that first usage of the weird wheelhouse/naming structure in the log, `setuptools_scm-6.4.2` is installed, which follows a different numbering scheme it seems. I'll try to pin that to something older as well

**Comment by tylerjereddy** [comment]
Err but SciPy `1.8.0` was released February 5 and didn't have this issue. `setuptools-scm 6.4.2` was released in January 2022, so there's no logical older pin to use really.

**Comment by tylerjereddy** [comment]
The `setuptools` pin is already present in the branched `pyproject.toml` as well.

**Comment by rgommers** [comment]
`setuptools_scm` shouldn't be relevant, it's only installed as a workaround for a `pytest-forked` issue (see commit ac96f14f73b14cb70fa9) and we're not using it for anything AFAIK.

**Comment by tylerjereddy** [comment]
I'm still ~99 % sure the problem is with `setuptools`, it is the exact problem I had locally. I've tried to pin in more places and I'll let this diff run overnight. Part of the problem is that there are `pip install` commands that happen inside and outside of the virtualenvs (etc.) that `multibuild` uses, which makes it non-trivial to reason about sometimes.

```diff
diff --git a/.travis.yml b/.travis.yml
index 88e7a23..23b9c44 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -151,7 +151,7 @@ before_install:
           CONTAINER=wheels;
           UPLOAD_ARGS="--no-update-index";
       fi
-    - BUILD_DEPENDS="wheel oldest-supported-numpy $CYTHON_BUILD_DEP $PYTHRAN_BUILD_DEP $PYBIND11_BUILD_DEP"
+    - BUILD_DEPENDS="wheel oldest-supported-numpy $CYTHON_BUILD_DEP $PYTHRAN_BUILD_DEP $PYBIND11_BUILD_DEP setuptools<60.0.0"
     - TEST_DEPENDS="oldest-supported-numpy pytest pytest-xdist pytest-faulthandler pytest-env"
     - source multibuild/common_utils.sh
     - source multibuild/travis_steps.sh
diff --git a/azure-posix.yml b/azure-posix.yml
index 6da3775..55320bb 100644
--- a/azure-posix.yml
+++ b/azure-posix.yml
@@ -62,7 +62,7 @@ jobs:
 
           pip install --upgrade virtualenv wheel
           pip install "setuptools<60.0.0"
-          BUILD_DEPENDS="wheel oldest-supported-numpy Cython>=0.29.24 pybind11>=2.4.3 pythran"
+          BUILD_DEPENDS="wheel oldest-supported-numpy Cython>=0.29.24 pybind11>=2.4.3 pythran setuptools<60.0.0"
 
           source multibuild/common_utils.sh
           source multibuild/travis_steps.sh

```

**Comment by tylerjereddy** [comment]
that did the trick, so back on track for releasing
