### ISSUE TITLE
SciPy nightly builds are failing because pooch is not installed

### ISSUE THREAD

**Issue by thomasjpfan** [MacPython/scipy-wheels#175]
The [nightly CI is failing](https://dev.azure.com/numpy/numpy/_build/results?buildId=25626&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=74b99ac4-969e-5d5f-3589-394e967bbd0f) because pooch is not installed.

Side note: Should test that require the network run by default? I think some package managers do not allow network access when testing a package.

**Comment by tylerjereddy** [comment]
FWIW, we're about to switch over to `cibuildwheel` for `1.9.2` onward, if all goes well, so maybe this will get managed over in the main repo.

From a quick check our new setup for `cibuildwheel`  in main repo `pyproject.toml` has `before-test = "pip install -r {project}/tools/wheels/test_requirements.txt"`

Where `test_requirements.txt` has `pooch` in it over in the main repo. So, probably "ok" over there assuming we switch wheels infra before `1.10`?

**Comment by thomasjpfan** [comment]
Thank you for the information. It looks like this issue will be resolved on the main repo.

**Comment by rgommers** [comment]
Yes, we're switching over. We should disable the nightly runs here though, no point keeping those going (also we don't want competing uploads to the Anaconda bucket. I'll open a PR for that.

**Comment by rgommers** [comment]
done in gh-176
