### ISSUE TITLE
Change branching strategy

### ISSUE THREAD

**Issue by pv** [MacPython/scipy-wheels#19]
I think it would make sense to change the branching strategy to match the scipy main repository:

- rename `daily -> master`, build daily builds from master
- each scipy release gets a separate `v1.0.x` branch

Then PRs automatically go to the right branch, and you don't have the issue that the build setup may change e.g. between rcX releases (which caused problems with numpy 1.13.x), or between bugfix point releases. If you need to upgrade the build setup for a `.x` branch, you can merge master to it.

(We should consider this only after 1.0.0 release, though.)

**Comment by matthew-brett** [comment]
Yes, that sounds like a good idea.

**Comment by rgommers** [comment]
+1

**Comment by pv** [comment]
Ok, changed branches and edited the configuration and documentation.
