### ISSUE TITLE
Move under scipy project

### ISSUE THREAD

**Issue by pv** [MacPython/scipy-wheels#20]
It could perhaps be more natural to have this repository under the scipy project, since it hasn't to do only with OSX, and the people who have business editing the configuration are already members of the scipy org.

**Comment by matthew-brett** [comment]
Fine with me.  Only downside is that it adds to the Scipy Travis-CI queue.

**Comment by pv** [comment]
I think the travis issue depends on which of scipy or macpython queues is also more saturated. The latter has the daily builds of many projects, so I'm not sure if there's a big difference.

**Comment by rgommers** [comment]
I think moving makes sense.

**Comment by h-vetinari** [comment]
Agreed that moving makes sense (just had to look up how something is built), finding it under `MacPython` on github is counter-intuitive.

**Comment by rgommers** [comment]
I'll close this, since we've moved wheel building to the main SciPy repo and using `cibuildwheel`. So no need to move this repo anymore (at this point that would just break some links, and not achieve much anymore).

**Comment by tupui** [comment]
@rgommers should we then archive the repo?

**Comment by rgommers** [comment]
Yes, I think that's about time. @tylerjereddy (or anyone else) - any reason not to archive this repo?

**Comment by tylerjereddy** [comment]
Yes, I think we probably should--I can't imagine it being worth it trying to get the CI working here again in any practical scenario.

**Comment by rgommers** [comment]
Thanks, I'll archive it now then. If needed, we can unarchive it.
