### ISSUE TITLE
Repeated timeouts for i686 on TravisCI

### ISSUE THREAD

**Issue by rgommers** [MacPython/scipy-wheels#22]
@matthew-brett there are four builds for i686 that have now timed out three times in a row. Any ideas of what's going on or how to work around it?

**Comment by rgommers** [comment]
End of log:
```
2c06c756b42e: Pull complete
d4409afcac6b: Pull complete
ebf27c54dbd8: Pull complete
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by rgommers** [comment]
It's only a couple of Linux wheels, so I'm going to ignore it for now - can be fixed after uploading to PyPI and announcing the release.

**Comment by matthew-brett** [comment]
It's happening on other builds too - I think it's a travis-ci problem - I've raised an issue.

**Comment by matthew-brett** [comment]
See the issue - it's being investigated.  It's nothing to do with 32-bit specifically.

I've restarted the failed builds, one has already passed, two are still building.  Would you mind pushing up the wheels when they're done?  I'm about go to offline for a few hours.

Crossref: https://github.com/scipy/scipy/issues/8077

**Comment by rgommers** [comment]
Thanks for uploading the remaining wheels.
