### ISSUE TITLE
1.0.x broken on macOS

### ISSUE THREAD

**Issue by rgommers** [MacPython/scipy-wheels#27]
See https://travis-ci.org/MacPython/scipy-wheels/builds/357678450, ends repeatably with `sudo: pip: command not found`. Looks like `multibuild` was updated for various macOS issues, so looks like the right fix is to update to latest `multibuild` also on the `1.0.x` branch. Opening this issue to ask if anyone sees an issue with that.

**Comment by rgommers** [comment]
Okay, gave that a try in 170955c

**Comment by rgommers** [comment]
Great, those builds errored after 5 minutes and TravisCI is not showing the full build log even with "raw log". That needs reverting (tomorrow), guess we'll try and cherry-pick the relevant macOS fixes. Not sure how well that works with a git submodule - is it a good idea to just add some commits directly to a submodule??

**Comment by pv** [comment]
I think it's not possible to add commits to a submodule, it always has to refer to a commit available on upstream.

**Comment by matthew-brett** [comment]
I will try and fix this up later today.

**Comment by pv** [comment]
Note that the new travis builds were terminated with an exclamation mark, not x --- I restarted the build in case this is just intermittent failure.

**Comment by pv** [comment]
Nope, still fails. Pushed a commit into v1.0.x that makes it use the same multibuild version as the weekly master branch builds, which seemed to be in working order.

**Comment by pv** [comment]
Travis build seems to pass OK with that version of multibuild.

**Comment by rgommers** [comment]
Ah I updated to `multibuild/master` while `multibuild/devel` is the one that worked. Thanks Pauli.

@matthew-brett would be useful to fast-forward `master` to `devel` perhaps?

**Comment by matthew-brett** [comment]
Multibuild master is nearly the same as multibuild devel though - just a few tiny differences.   The version of multibuild in the scipy-wheels / master branch is a fair bit behind.  I'm just trying to work out where the damage comes from : 

* https://github.com/matthew-brett/scipy-wheels/tree/mb-1.0.x-testing

**Comment by matthew-brett** [comment]
Now building correctly on multibuild master - so not sure what the problem was:  https://travis-ci.org/matthew-brett/scipy-wheels/builds/357931159 - maybe https://www.traviscistatus.com/incidents/n0f1kmm5k4x5

**Comment by matthew-brett** [comment]
Aha - sorry - there is a bug in the `suppress` macro - but the libwebp and szip builds are failing - search the log for `tar: Unrecognized archive format`
