### ISSUE TITLE
Does pip build isolation break manylinux builds?

### ISSUE THREAD

**Issue by pv** [MacPython/scipy-wheels#28]
@matthew-brett: pip 10 was released today and it adds support for `pyproject.toml`.

This makes pip commands, including `pip wheel`, to setup a build environment with e.g. numpy versions specified in `pyproject.toml`.

What does this imply for multibuild?

The scipy-wheels windows builds are unaffected since they do `python setup.py bdist_wheel`.

Is there a way to force multibuild to use `setup.py bdist_wheel` instead of `pip wheel` to do the build?

**Comment by pv** [comment]
Of course, these things drop by immediately when you promised the release is due :)

**Comment by matthew-brett** [comment]
Yes, we can force multibuild to use use `python setup.py bdist_wheel`, by using `build_bdist_wheel` instead of `build_wheel` in `.travis.yml`.  But - does pip's behavior change if there is no `pyproject.toml`?

**Comment by charris** [comment]
The NumPy daily build failed this morning, I was wondering if it something was pip related. The error is
```
Traceback (most recent call last):
  File "/io/multibuild/supported_wheels.py", line 9, in <module>
    from pip.pep425tags import get_supported
ImportError: No module named pep425tags
ERROR: You must give at least one requirement to install (maybe you meant "pip install https://nipy.bic.berkeley.edu/manylinux"?)
```

**Comment by matthew-brett** [comment]
Aha - no - that's multibuild using the pip API, which has been removed in the latest release.  I'll look into it.

**Comment by pv** [comment]
Removing `pyproject.toml` afaik fully disables the feature, so I think this is not blocking scipy 1.1.0.

**Comment by pv** [comment]
The pep425tags issue however is blocking...

**Comment by matthew-brett** [comment]
I've put in a fix to multibuild devel, and I've update numpy-wheels to that commit, but it's waiting on the new scipy-wheels build.

**Comment by charris** [comment]
Works on Mac, fails on linux, but different error.

**Comment by pv** [comment]
For 1.1.x I'll pin pip==9.0.3 to get the linux/osx builds going.
