### ISSUE TITLE
Creating 3.8.0rc1 wheels

### ISSUE THREAD

**Issue by mattip** [MacPython/scipy-wheels#49]
multibuild and manylinux should now work with 3.8.0rc1, see MacPython/numpy-wheels#64 and MacPython/numpy-wheels#62. It is important to update multibuild to the HEAD of the latest `devel` branch.

I am not sure if scipy wants to try this now, 3.8 final is supposed to come out in a week or so.

**Comment by tylerjereddy** [comment]
Thanks Matti -- I'm just resurfacing after resubmitting the SciPy paper & working on grant stuff. Hopefully I can look into this soon. I have been watching what you & Chuck have been doing from a distance..

**Comment by tylerjereddy** [comment]
@charris @mattip Is 3.8 working pretty well with NumPy wheels these days? I'll try to look through the links above soon-ish as we try to get `1.3.2` out on our end.

**Comment by mattip** [comment]
It should just work. You might want to change the 3.8-dev travis job to 3.8, I see [travis supports it](https://docs.travis-ci.com/user/languages/python/#specifying-python-versions). In scipy-wheels, you should update the multibuild subrepo to the `devel` branch HEAD and copy the 3.8 specs from the numpy-wheels repo.

**Comment by tylerjereddy** [comment]
I think we're in better shape for basic Python 3.8 support now, so I'll close this. Will likely do a 1.3.3 release to deal with some DLL issues that snuck through on Windows, time permitting with 1.4.x in the pipeline.
