### ISSUE TITLE
master branch is way behind daily branch

### ISSUE THREAD

**Issue by rgommers** [MacPython/scipy-wheels#6]
This looks completely wrong, what's going on? There's no mention in the README of the ``daily`` branch, however recent fixes went into that. The ``master`` branch misses license changes etc.

**Comment by matthew-brett** [comment]
My idea was to make the daily branch one where we can put fixes for current scipy master, leaving the master branch capable of building the last release.  But then merging daily into master from time to time.  I'll do that now.

**Comment by rgommers** [comment]
I guess that's a reasonable strategy, then we can more easily experiment with CI changes. It just needs documenting in big bold letters at the top of README. Including to send PRs against ``daily`` then.

**Comment by rgommers** [comment]
Fixed, thanks!

**Comment by rgommers** [comment]
I couldn't have timed this much worse:

![image](https://user-images.githubusercontent.com/98330/30520020-f42220be-9bf8-11e7-89f8-b701baa34e88.png)

Scheduled maintenance for the next 1.5 hours.

**Comment by matthew-brett** [comment]
Oops. 

I merged the doc update with `[skip ci]` - so I hope that won't clog.

**Comment by rgommers** [comment]
It still triggered Appveyor, but that cancelled on merge - so all good.

**Comment by pv** [comment]
@matthew-brett: the merge in aa59575ce7003f5827642b9e980d4b9d4486f2a2 reset BUILD_COMMIT back to v0.19.1

**Comment by pv** [comment]
I canceled the Appveyor builds which were building the wrong commit, and pushed a new build commit to master.

**Comment by pv** [comment]
Ah ok, no --- the issue was that Ralf changed BUILD_COMMIT to 1.0.0b1 only for travis but not for appveyor. Anyway, it should be in order now.

**Comment by rgommers** [comment]
> only for travis but not for appveyor.

I was tired enough to not think hard anymore and just followed the instructions in README. Those only say to change ``.travis.yml``.

thanks for restarting the build
