### ISSUE TITLE
MAINT: Timestamp nightly wheel filenames

### ISSUE THREAD

**Issue by tylerjereddy** [MacPython/scipy-wheels#77]
Based on discussion with @mattip in #74, downstream projects using `pip` to pull in our wheels from the nightly (weekly) anaconda.org repo appear to need dates stamped right into filenames, presumably because `pip` is not scraping timestamp metadata  directly from the uploaded files.

So it just kind of arbitrarily sorts by hash alphanumerically, which is bad.

While I'd prefer if there were a simple `pip install` flag of some sort that "just worked" for pulling in the latest based on metadata, I'll open this issue to try to get done soon-ish.

At least for us, we only need to worry about Travis--we haven't done nightlies for Windows/Appveyor in recent history AFAIK.

**Comment by bashtage** [comment]
I don't think you have to timestamp.  You could also use the structure

```
scipy-1.5.0.dev0+NUMBER_OF_COMMITS_AFTER_dev0.g6fd3052-cp38-cp38-macosx_10_9_x86_64.whl
```

**Comment by tylerjereddy** [comment]
Following the merging of the cross-linked PR above--I should check mid-weed after the Tuesday "nightly" upload to see if the wheels are properly named for downstream `pip` download purposes.

**Comment by tylerjereddy** [comment]
The timestamping appears to have worked as intended for the weekly uploads last Tuesday: https://anaconda.org/scipy-wheels-nightly/scipy/files

I've also manually purged the older weekly wheel uploads, with incorrect file naming, to prevent interference with automated downloads from downstream projects using `pip` in CI, etc.

So, I'll close this issue. @bashtage -- feel free to open an issue/ping me if `statsmodels` or other projects are having issues with our weekly wheels.
