### ISSUE TITLE
Upgrade numpy/f2py in the builds separately?

### ISSUE THREAD

**Issue by pv** [MacPython/scipy-wheels#85]
We might want to consider using a newer f2py version for building Scipy, than what is provided by the version of Numpy we are using for ABI compatibility. How to do this would be similar to what was done with `numpy-distutils` in the Windows builds.

Why to do this would be to take advantage of f2py bugfixes (eg. https://github.com/numpy/numpy/pull/16519) that may be beneficial to have.

**Comment by rgommers** [comment]
This is still a relevant idea, but we'll probably only revisit it when there's an urgent need. Closing this issue, since we're archiving this repo.
